osx_image: xcode10
language: objective-c
script:
- sudo gem install cocoapods -v 1.5.3
- travis_retry pod repo update > /dev/null
- pod lib lint --use-libraries --allow-warnings || pod lib lint --allow-warnings
